// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.20.1
// source: gpt.proto

package gpt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GPTRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *GPTRequest) Reset() {
	*x = GPTRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPTRequest) ProtoMessage() {}

func (x *GPTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPTRequest.ProtoReflect.Descriptor instead.
func (*GPTRequest) Descriptor() ([]byte, []int) {
	return file_gpt_proto_rawDescGZIP(), []int{0}
}

func (x *GPTRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GPTReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GPTReply) Reset() {
	*x = GPTReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gpt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPTReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPTReply) ProtoMessage() {}

func (x *GPTReply) ProtoReflect() protoreflect.Message {
	mi := &file_gpt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPTReply.ProtoReflect.Descriptor instead.
func (*GPTReply) Descriptor() ([]byte, []int) {
	return file_gpt_proto_rawDescGZIP(), []int{1}
}

func (x *GPTReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gpt_proto protoreflect.FileDescriptor

var file_gpt_proto_rawDesc = []byte{
	0x0a, 0x09, 0x67, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x67, 0x70, 0x74,
	0x22, 0x26, 0x0a, 0x0a, 0x47, 0x50, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x24, 0x0a, 0x08, 0x47, 0x50, 0x54, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x74,
	0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x47, 0x50, 0x54, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0f, 0x2e, 0x67, 0x70, 0x74,
	0x2e, 0x47, 0x50, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x67, 0x70,
	0x74, 0x2e, 0x47, 0x50, 0x54, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x47, 0x50, 0x54, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x0f, 0x2e, 0x67, 0x70, 0x74, 0x2e, 0x47, 0x50, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0d, 0x2e, 0x67, 0x70, 0x74, 0x2e, 0x47, 0x50, 0x54, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x30, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x67, 0x70, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gpt_proto_rawDescOnce sync.Once
	file_gpt_proto_rawDescData = file_gpt_proto_rawDesc
)

func file_gpt_proto_rawDescGZIP() []byte {
	file_gpt_proto_rawDescOnce.Do(func() {
		file_gpt_proto_rawDescData = protoimpl.X.CompressGZIP(file_gpt_proto_rawDescData)
	})
	return file_gpt_proto_rawDescData
}

var file_gpt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gpt_proto_goTypes = []interface{}{
	(*GPTRequest)(nil), // 0: gpt.GPTRequest
	(*GPTReply)(nil),   // 1: gpt.GPTReply
}
var file_gpt_proto_depIdxs = []int32{
	0, // 0: gpt.Greeter.GetGPTMessage:input_type -> gpt.GPTRequest
	0, // 1: gpt.Greeter.GetGPTStreamData:input_type -> gpt.GPTRequest
	1, // 2: gpt.Greeter.GetGPTMessage:output_type -> gpt.GPTReply
	1, // 3: gpt.Greeter.GetGPTStreamData:output_type -> gpt.GPTReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gpt_proto_init() }
func file_gpt_proto_init() {
	if File_gpt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gpt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPTRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gpt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPTReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gpt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gpt_proto_goTypes,
		DependencyIndexes: file_gpt_proto_depIdxs,
		MessageInfos:      file_gpt_proto_msgTypes,
	}.Build()
	File_gpt_proto = out.File
	file_gpt_proto_rawDesc = nil
	file_gpt_proto_goTypes = nil
	file_gpt_proto_depIdxs = nil
}
