// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.1
// source: gpt.proto

package gpt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Greeter_GetGPTMessage_FullMethodName    = "/gpt.Greeter/GetGPTMessage"
	Greeter_GetGPTStreamData_FullMethodName = "/gpt.Greeter/GetGPTStreamData"
)

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	GetGPTMessage(ctx context.Context, in *GPTRequest, opts ...grpc.CallOption) (*GPTReply, error)
	GetGPTStreamData(ctx context.Context, in *GPTRequest, opts ...grpc.CallOption) (Greeter_GetGPTStreamDataClient, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetGPTMessage(ctx context.Context, in *GPTRequest, opts ...grpc.CallOption) (*GPTReply, error) {
	out := new(GPTReply)
	err := c.cc.Invoke(ctx, Greeter_GetGPTMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetGPTStreamData(ctx context.Context, in *GPTRequest, opts ...grpc.CallOption) (Greeter_GetGPTStreamDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], Greeter_GetGPTStreamData_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterGetGPTStreamDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_GetGPTStreamDataClient interface {
	Recv() (*GPTReply, error)
	grpc.ClientStream
}

type greeterGetGPTStreamDataClient struct {
	grpc.ClientStream
}

func (x *greeterGetGPTStreamDataClient) Recv() (*GPTReply, error) {
	m := new(GPTReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	GetGPTMessage(context.Context, *GPTRequest) (*GPTReply, error)
	GetGPTStreamData(*GPTRequest, Greeter_GetGPTStreamDataServer) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) GetGPTMessage(context.Context, *GPTRequest) (*GPTReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGPTMessage not implemented")
}
func (UnimplementedGreeterServer) GetGPTStreamData(*GPTRequest, Greeter_GetGPTStreamDataServer) error {
	return status.Errorf(codes.Unimplemented, "method GetGPTStreamData not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_GetGPTMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GPTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetGPTMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_GetGPTMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetGPTMessage(ctx, req.(*GPTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetGPTStreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GPTRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).GetGPTStreamData(m, &greeterGetGPTStreamDataServer{stream})
}

type Greeter_GetGPTStreamDataServer interface {
	Send(*GPTReply) error
	grpc.ServerStream
}

type greeterGetGPTStreamDataServer struct {
	grpc.ServerStream
}

func (x *greeterGetGPTStreamDataServer) Send(m *GPTReply) error {
	return x.ServerStream.SendMsg(m)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gpt.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGPTMessage",
			Handler:    _Greeter_GetGPTMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetGPTStreamData",
			Handler:       _Greeter_GetGPTStreamData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gpt.proto",
}
